[package]
name = "ulmake"
version = "0.1.0"
edition = "2018"
authors = ["xadrianzetx"]
license = "MIT"
repository = ""
escription = ""

[dependencies]
iso9660 = {version = "0.1.0", git = "https://github.com/ids1024/iso9660-rs"}
regex = "1.5"
fs2 = "0.4.3"